/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AcademicLeader;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class AssignLecturerFrame extends javax.swing.JFrame {
    
    private String currentLeaderID;

    /**
     * Creates new form AssignLecturer
     */
    public AssignLecturerFrame(String leaderID) {
    initComponents();
    this.currentLeaderID = leaderID;
    loadModules();
    loadLecturers();
    }
    
    private void loadModules() {
    cmbModule.removeAllItems();

    try (BufferedReader br = new BufferedReader(new FileReader("module.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(";");

            // only this Academic Leader's modules
            if (data[2].equals(currentLeaderID)) {
                cmbModule.addItem(data[0]); // moduleID
            }
        }
    } catch (IOException e) {}
    }
    
    private void loadLecturers() {
    cmbLecturer.removeAllItems();

    try (BufferedReader br = new BufferedReader(new FileReader("account.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(";");

            if (data[8].equals("Lecturer")) {
                cmbLecturer.addItem(data[0]); // lecturerID
            }
        }
    } catch (IOException e) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbModule = new javax.swing.JComboBox<>();
        cmbLecturer = new javax.swing.JComboBox<>();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setText("Assign Lecturer");

        cmbModule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbLecturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Module :");

        jLabel3.setText("Lecturer :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnAssign)
                .addGap(39, 39, 39)
                .addComponent(btnBack)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(38, 38, 38)
                            .addComponent(cmbModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(btnBack))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
 if (cmbModule.getSelectedItem() == null || cmbLecturer.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Please select module and lecturer");
        return;
    }

    String moduleID = cmbModule.getSelectedItem().toString();
    String lecturerID = cmbLecturer.getSelectedItem().toString();

    // check lecturer already assigned
    try (BufferedReader br = new BufferedReader(new FileReader("module.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            if (line.endsWith(";" + lecturerID)) {
                JOptionPane.showMessageDialog(this, "Lecturer already assigned to a module");
                return;
            }
        }
    } catch (IOException e) {}

    ArrayList<String> updated = new ArrayList<>();

    try (BufferedReader br = new BufferedReader(new FileReader("module.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(";");

            if (data[0].equals(moduleID) && data[2].equals(currentLeaderID)) {
                data[3] = lecturerID; // assign lecturer
                line = String.join(";", data);
            }
            updated.add(line);
        }
    } catch (IOException e) {}

    try (PrintWriter pw = new PrintWriter(new FileWriter("module.txt"))) {
        for (String l : updated) pw.println(l);
    } catch (IOException e) {}

    JOptionPane.showMessageDialog(this, "Lecturer assigned successfully");        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    new AcademicLeaderDashboard(currentLeaderID).setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbLecturer;
    private javax.swing.JComboBox<String> cmbModule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
