/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AcademicLeader;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class ModuleManagementFrame extends javax.swing.JFrame {

    private final String currentLeaderID;
    private final ModuleRepository repo = new ModuleRepository("Module.txt");
    



    /**
     * Creates new form ModuleManagement
     *
     * @param leaderID
     */
    public ModuleManagementFrame(String leaderID) {
        initComponents();
        this.currentLeaderID = leaderID;
        loadModules();
        

    }

    private void loadModules() {
        DefaultTableModel model = (DefaultTableModel) tblModule.getModel();
        model.setRowCount(0);

        try {
            for (String line : repo.readAllLines()) {
                if (line.trim().isEmpty()) continue;

                String[] data = line.split(";");
                if (data.length >= 4 && data[2].equals(currentLeaderID)) {
                    model.addRow(new Object[]{ data[0], data[1], data[2], data[3] });
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "File error: " + e.getMessage());
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblModule = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtModuleID = new javax.swing.JTextField();
        txtModuleName = new javax.swing.JTextField();
        btnUpdateActionPerformed = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblModule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Module ID", "Module Name", "Academic Leader ID", "Lecturer ID"
            }
        ));
        tblModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblModuleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblModule);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setText("Module Management");

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtModuleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModuleIDActionPerformed(evt);
            }
        });

        txtModuleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModuleNameActionPerformed(evt);
            }
        });

        btnUpdateActionPerformed.setText("Update");
        btnUpdateActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformedActionPerformed(evt);
            }
        });

        jButton8.setText("Create");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtModuleID, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtModuleName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(29, 29, 29)
                                .addComponent(btnUpdateActionPerformed)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addGap(31, 31, 31)
                                .addComponent(jButton5)
                                .addGap(41, 41, 41)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModuleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(btnUpdateActionPerformed)
                    .addComponent(jButton8))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformedActionPerformed
        int row = tblModule.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a module");
            return;
        }

        String moduleID = txtModuleID.getText().trim();
        String newName  = txtModuleName.getText().trim();

        if (moduleID.isEmpty() || newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in Module ID and Module Name");
            return;
        }

        ArrayList<String> updated = new ArrayList<>();

        try {
            for (String line : repo.readAllLines()) {
                if (line.trim().isEmpty()) continue;

                String[] data = line.split(";");
                if (data.length >= 4 && data[0].equals(moduleID) && data[2].equals(currentLeaderID)) {
                    data[1] = newName;
                    line = String.join(";", data);
                }
                updated.add(line);
            }

            repo.writeAllLines(updated);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "File error: " + e.getMessage());
            e.printStackTrace();
            return;
        }

        JOptionPane.showMessageDialog(this, "Module updated");
        loadModules();
    }//GEN-LAST:event_btnUpdateActionPerformedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = tblModule.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a module first");
            return;
        }

        String moduleID = txtModuleID.getText().trim();
        if (moduleID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Module ID is empty");
            return;
        }

        ArrayList<String> updated = new ArrayList<>();

        try {
            for (String line : repo.readAllLines()) {
                if (line.trim().isEmpty()) continue;

                String[] data = line.split(";");
                if (data.length >= 4 && !(data[0].equals(moduleID) && data[2].equals(currentLeaderID))) {
                    updated.add(line);
                }
            }

            repo.writeAllLines(updated);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "File error: " + e.getMessage());
            e.printStackTrace();
            return;
        }

        JOptionPane.showMessageDialog(this, "Module deleted");
        loadModules();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String moduleID   = txtModuleID.getText().trim();
        String moduleName = txtModuleName.getText().trim();

        if (moduleID.isEmpty() || moduleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields");
            return;
        }

        try {
            for (String line : repo.readAllLines()) {
                if (line.startsWith(moduleID + ";")) {
                    JOptionPane.showMessageDialog(this, "Module ID already exists");
                    return;
                }
            }

            repo.appendLine(moduleID + ";" + moduleName + ";" + currentLeaderID + ";-");

            JOptionPane.showMessageDialog(this, "Module created successfully");
            System.out.println("MODULE USED = " + repo.getFile().getAbsolutePath());
            loadModules();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving module: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtModuleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModuleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModuleIDActionPerformed

    private void txtModuleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModuleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModuleNameActionPerformed

    private void tblModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModuleMouseClicked
        int row = tblModule.getSelectedRow();

        if (row != -1) {
            txtModuleID.setText(tblModule.getValueAt(row, 0).toString());
            txtModuleName.setText(tblModule.getValueAt(row, 1).toString());
            txtModuleID.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblModuleMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new AcademicLeaderDashboard(currentLeaderID).setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateActionPerformed;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblModule;
    private javax.swing.JTextField txtModuleID;
    private javax.swing.JTextField txtModuleName;
    // End of variables declaration//GEN-END:variables
}
