/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import LogIn.LogIn;

/**
 *
 * @author Xenia Thor
 */
public class feedbackForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(feedbackForm.class.getName());

    private java.util.Map<String, String> classNameToIdMap = new java.util.HashMap<>();

    public feedbackForm(){
        initComponents();
        btnTitle.setText("Choose which class to comment on");
        loadClassesIntoComboBox();
        setLocationRelativeTo(null);
    }

    private void loadClassesIntoComboBox(){
        jComboBox1.removeAllItems();
        classNameToIdMap.clear();

        String studentID = LogIn.accID;
        if (studentID == null || studentID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please log in first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.util.ArrayList<String> registeredClassIDs = new java.util.ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("src/TextFiles/Registration.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.trim().split(";");
                if (parts.length >= 2 && parts[0].trim().equals(studentID)) {
                    for (int i = 1; i < parts.length; i++) {
                        registeredClassIDs.add(parts[i].trim());
                    }
                    break;
                }
            }
        } catch (IOException e) {
            // Registration file doesn't exist
        }

        if (registeredClassIDs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "You have not registered for any classes yet.\nPlease register for classes first.", "No Classes", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader("src/TextFiles/Class.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {

                if (!line.trim().isEmpty()) {
                    String[] part = line.split(";");
                    if (part.length >= 3) {
                        String classId = part[0].trim();
                        String moduleName = part[2].trim(); // Display Module Name

                        if (registeredClassIDs.contains(classId)) {
                            jComboBox1.addItem(moduleName);
                            classNameToIdMap.put(moduleName, classId);
                        }
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        if (jComboBox1.getItemCount() > 0) {
            // No module loading needed
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JToggleButton();
        btnCancel = new javax.swing.JToggleButton();
        btnTitle = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCheckIndividualResult1 = new javax.swing.JButton();
        btnComment1 = new javax.swing.JButton();
        btnRegisterClass1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.setPreferredSize(new java.awt.Dimension(80, 30));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(80, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnTitle.setFont(new java.awt.Font("Eras Light ITC", 1, 20)); // NOI18N
        btnTitle.setText("Choose which class to comment on");

        lblClass.setText("Select Class:");

        jPanel1.setBackground(new java.awt.Color(181, 172, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 400));

        btnCheckIndividualResult1.setBackground(new java.awt.Color(181, 172, 252));
        btnCheckIndividualResult1.setText("Check Individual Result");
        btnCheckIndividualResult1.setBorder(null);
        btnCheckIndividualResult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIndividualResult1ActionPerformed(evt);
            }
        });

        btnComment1.setBackground(new java.awt.Color(219, 218, 224));
        btnComment1.setText("Comment");
        btnComment1.setBorder(null);
        btnComment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComment1ActionPerformed(evt);
            }
        });

        btnRegisterClass1.setBackground(new java.awt.Color(181, 172, 252));
        btnRegisterClass1.setText("Register Class");
        btnRegisterClass1.setBorder(null);
        btnRegisterClass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterClass1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegisterClass1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCheckIndividualResult1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(btnComment1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnRegisterClass1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckIndividualResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComment1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnHome)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addGap(10, 10, 10)
                .addComponent(btnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // LearningPage selection changed - no module loading needed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        StudentDashboard main = new StudentDashboard();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String selectedClassName = (String) jComboBox1.getSelectedItem();

        if (selectedClassName == null || selectedClassName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a class first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String classId = classNameToIdMap.get(selectedClassName);
        JDialogFeedback dialog = new JDialogFeedback(this, true, classId, selectedClassName);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCheckIndividualResult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckIndividualResult1ActionPerformed
        Assessment checkMark = new Assessment();
        checkMark.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCheckIndividualResult1ActionPerformed

    private void btnComment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComment1ActionPerformed
        feedbackForm comment = new feedbackForm();
        comment.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComment1ActionPerformed

    private void btnRegisterClass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterClass1ActionPerformed
        LearningPage registerClass = new LearningPage();
        registerClass.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegisterClass1ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        StudentDashboard home = new StudentDashboard();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new feedbackForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancel;
    private javax.swing.JButton btnCheckIndividualResult1;
    private javax.swing.JButton btnComment1;
    private javax.swing.JButton btnHome;
    private javax.swing.JToggleButton btnOk;
    private javax.swing.JButton btnRegisterClass1;
    private javax.swing.JLabel btnTitle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClass;
    // End of variables declaration//GEN-END:variables
}
