/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Student;

import LogIn.LogIn;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Xenia Thor
 */
public class JDialogProgress extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogProgress.class.getName());

    private String classId;
    private String className;

    public JDialogProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public JDialogProgress(java.awt.Frame parent, boolean modal, String classId, String className) {
        super(parent, modal);
        this.classId = classId;
        this.className = className;
        initComponents();
        setLocationRelativeTo(parent);

        lblTitle.setText("Progress for " + className);
        setTitle("Progress - " + className);
        loadProgress();
    }

    private void loadProgress() {
        String studentID = LogIn.accID;
        if (studentID == null || studentID.isEmpty()) return;

        // --- Class Test Status ---
        String classTestStatus = "Not submitted";
        try (BufferedReader br = new BufferedReader(new FileReader("src/TextFiles/ClassTestSubmission.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] parts = line.split(";");
                // Format: StudentID;ClassID;Answers;DateTime;Status[;Score]
                if (parts.length >= 6
                        && parts[0].trim().equals(studentID)
                        && parts[1].trim().equals(classId)) {
                    String status = parts[5].trim();
                    String date = parts[4].trim();
                    classTestStatus = status + "  (" + date + ")";
                }
            }
        } catch (IOException e) {
            // File doesn't exist yet
        }
        lblClassTestStatus.setText(classTestStatus);

        // --- Assignment Status ---
        String assignmentStatus = "Not submitted";
        try (BufferedReader br = new BufferedReader(new FileReader("src/TextFiles/AssignmentSubmission.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] parts = line.split(";");
                // Format: StudentID;ClassID;DateTime;Status
                if (parts.length >= 5
                        && parts[0].trim().equals(studentID)
                        && parts[1].trim().equals(classId)
                        && parts[2].trim().equals(className)) {
                    String status = parts[4].trim();
                    String date = parts[3].trim();
                    assignmentStatus = status + "  (" + date + ")";
                }
            }
        } catch (IOException e) {
            // File doesn't exist yet
        }
        lblAssignmentStatus.setText(assignmentStatus);

        // --- Grade Status ---
        String gradeStatus = "Not graded";
        try (BufferedReader br = new BufferedReader(new FileReader("src/TextFiles/AssessmentMark.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] parts = line.split(";");
                // Format: StudentID;ClassID;Grade;CGPA
                if (parts.length >= 4
                        && parts[0].trim().equals(studentID)
                        && parts[1].trim().equals(classId)) {
                    gradeStatus = parts[2].trim() + "  (CGPA: " + parts[3].trim() + ")";
                }
            }
        } catch (IOException e) {
            // File doesn't exist yet
        }
        lblGradeStatus.setText(gradeStatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblClassTestLabel = new javax.swing.JLabel();
        lblClassTestStatus = new javax.swing.JLabel();
        lblAssignmentLabel = new javax.swing.JLabel();
        lblAssignmentStatus = new javax.swing.JLabel();
        lblGradeLabel = new javax.swing.JLabel();
        lblGradeStatus = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class Progress");

        jPanel1.setBackground(new java.awt.Color(181, 172, 252));

        lblTitle.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lblTitle.setText("Class Progress");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        lblClassTestLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblClassTestLabel.setText("Class Test:");

        lblClassTestStatus.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblClassTestStatus.setText("Not submitted");

        lblAssignmentLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblAssignmentLabel.setText("Assignment:");

        lblAssignmentStatus.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblAssignmentStatus.setText("Not submitted");

        lblGradeLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblGradeLabel.setText("Overall Grade:");

        lblGradeStatus.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblGradeStatus.setText("Not graded");

        btnOk.setText("OK");
        btnOk.setPreferredSize(new java.awt.Dimension(80, 30));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClassTestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblClassTestStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAssignmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblAssignmentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblGradeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassTestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassTestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAssignmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGradeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            JDialogProgress dialog = new JDialogProgress(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAssignmentLabel;
    private javax.swing.JLabel lblAssignmentStatus;
    private javax.swing.JLabel lblClassTestLabel;
    private javax.swing.JLabel lblClassTestStatus;
    private javax.swing.JLabel lblGradeLabel;
    private javax.swing.JLabel lblGradeStatus;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
