/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

import LogIn.LogIn;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author Xenia Thor
 */
public class LearningPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LearningPage.class.getName());

    private ArrayList<String[]> studentCourses = new ArrayList<>();
    private int currentCourseIndex = 0;
    public static String currentClassID = "";
    public static String currentClassName = "";

    /**
     * Creates new form RegisterClass
     */
    public LearningPage() {
        initComponents();
        loadStudentCourses();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        btnPrevCourse = new javax.swing.JButton();
        labelCourseName = new javax.swing.JLabel();
        btnNextCourse = new javax.swing.JButton();
        labelCourseIndex = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNext2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Course");

        label1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        label1.setText("My Course");

        btnPrevCourse.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnPrevCourse.setText("<");
        btnPrevCourse.setPreferredSize(new java.awt.Dimension(50, 30));
        btnPrevCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevCourseActionPerformed(evt);
            }
        });

        labelCourseName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelCourseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCourseName.setText("Loading...");

        btnNextCourse.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnNextCourse.setText(">");
        btnNextCourse.setPreferredSize(new java.awt.Dimension(50, 30));
        btnNextCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextCourseActionPerformed(evt);
            }
        });

        labelCourseIndex.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelCourseIndex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCourseIndex.setText(" ");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Progress");

        btnNext.setText("VIEW");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Class Test");

        btnNext1.setText("NEXT");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Submit Assignment");

        btnNext2.setText("NEXT");
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(181, 172, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 400));

        btnBack.setActionCommand("BACK");
        btnBack.setLabel("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCourseIndex, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrevCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(labelCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNextCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCourseIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (!currentClassID.isEmpty()) {
            showProgressDialog();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        if (!currentClassID.isEmpty()) {
            ClassTest classTest = new ClassTest(currentClassID, currentClassName);
            classTest.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        SubmitHW submit = new SubmitHW(currentClassID, currentClassName);
        submit.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Registration registration = new Registration();
        registration.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrevCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevCourseActionPerformed
        if (!studentCourses.isEmpty()) {
            currentCourseIndex = (currentCourseIndex - 1 + studentCourses.size()) % studentCourses.size();
            updateCourseDisplay();
        }
    }//GEN-LAST:event_btnPrevCourseActionPerformed

    private void btnNextCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextCourseActionPerformed
        if (!studentCourses.isEmpty()) {
            currentCourseIndex = (currentCourseIndex + 1) % studentCourses.size();
            updateCourseDisplay();
        }
    }//GEN-LAST:event_btnNextCourseActionPerformed

    private void showProgressDialog() {
        JDialogProgress dialog = new JDialogProgress(this, true, currentClassID, currentClassName);
        dialog.setVisible(true);
    }

    private void loadStudentCourses() {
        studentCourses.clear();
        String studentID = LogIn.loggedInID;

        if (studentID == null || studentID.isEmpty()) {
            currentCourseIndex = 0;
            updateCourseDisplay();
            return;
        }

        ArrayList<String> classIDs = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("src/TextFiles/Registration.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.trim().split(";");
                if (parts.length >= 2 && parts[0].trim().equals(studentID)) {
                    for (int i = 1; i < parts.length; i++) {
                        classIDs.add(parts[i].trim());
                    }
                    break;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading Registration file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        for (String classID : classIDs) {
            String className = "";
            try (BufferedReader br = new BufferedReader(new FileReader("src/TextFiles/Class.txt"))) {
                String line;
                while ((line = br.readLine()) != null) {
                    String[] parts = line.trim().split(";");
                    if (parts.length >= 3 && parts[2].trim().equals(classID)) {
                        className = parts[1].trim();
                        break;
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error reading Class file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            String[] classInfo = {classID, className};
            studentCourses.add(classInfo);
        }

        currentCourseIndex = 0;
        updateCourseDisplay();
    }

    private void updateCourseDisplay() {
        if (studentCourses.isEmpty()) {
            labelCourseName.setText("No courses registered");
            labelCourseIndex.setText("");
            currentClassID = "";
            currentClassName = "";
            btnPrevCourse.setEnabled(false);
            btnNextCourse.setEnabled(false);
            btnNext.setEnabled(false);
            btnNext1.setEnabled(false);
            btnNext2.setEnabled(false);
        } else {
            String[] course = studentCourses.get(currentCourseIndex);
            currentClassID = course[0];
            currentClassName = course[1];
            labelCourseName.setText(currentClassName);
            labelCourseIndex.setText((currentCourseIndex + 1) + " / " + studentCourses.size());
            btnPrevCourse.setEnabled(true);
            btnNextCourse.setEnabled(true);
            btnNext.setEnabled(true);
            btnNext1.setEnabled(true);
            btnNext2.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LearningPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnNextCourse;
    private javax.swing.JButton btnPrevCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JLabel labelCourseIndex;
    private javax.swing.JLabel labelCourseName;
    // End of variables declaration//GEN-END:variables
}
