/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminStaff;

import Navigation.NavigateToLogInPage;
import javax.swing.JFrame;

/**
 *
 * @author Xinn
 */
public class AdminStaffDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminStaffDashboard.class.getName());

    /**
     * Creates new form ASDashboard
     */
    public AdminStaffDashboard(String adminName) {
        initComponents();
        jLabelWelcomeAdminStaff.setText("Welcome " + adminName + "!");
    }
    
    public void goToManageAccountDashboard(JFrame currentFrame) {
        ManageAccount manageAccountDashboard = new ManageAccount();
        manageAccountDashboard.setVisible(true);
        manageAccountDashboard.setLocationRelativeTo(null); // center on screen

        // Close the current frame
        if (currentFrame != null) {
            currentFrame.dispose();
        }
    }

    public void goToAssignLecturerDashboard(JFrame currentFrame) {
        AssignLecturer assignLecturerDashboard = new AssignLecturer();
        assignLecturerDashboard.setVisible(true);
        assignLecturerDashboard.setLocationRelativeTo(null); // center on screen

        // Close the current frame
        if (currentFrame != null) {
            currentFrame.dispose();
        }
    }
    
    public void goToCreateClassDashboard(JFrame currentFrame) {
        CreateClass createClassDashboard = new CreateClass();
        createClassDashboard.setVisible(true);
        createClassDashboard.setLocationRelativeTo(null); // center on screen

        // Close the current frame
        if (currentFrame != null) {
            currentFrame.dispose();
        }
    }
    
    public void goToAPUGradingSystem(JFrame currentFrame) {
        GradingSystem defineGradingSystemDashboard = new GradingSystem();
        defineGradingSystemDashboard.setVisible(true);
        defineGradingSystemDashboard.setLocationRelativeTo(null); // center on screen

        // Close the current frame
        if (currentFrame != null) {
            currentFrame.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccountManage = new javax.swing.JButton();
        btnAssignLecturer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGradingSystem = new javax.swing.JButton();
        btnCreateClass = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabelWelcomeAdminStaff = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAccountManage.setText("Manage Account");
        btnAccountManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountManageActionPerformed(evt);
            }
        });

        btnAssignLecturer.setText("Assign Lecturer");
        btnAssignLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignLecturerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setText("Administrator Dashboard");

        btnGradingSystem.setText("Grading System");
        btnGradingSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradingSystemActionPerformed(evt);
            }
        });

        btnCreateClass.setText("Create Class");
        btnCreateClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateClassActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabelWelcomeAdminStaff.setText("Welcome xx!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogOut)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAccountManage)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnAssignLecturer)
                                        .addGap(38, 38, 38)
                                        .addComponent(btnGradingSystem)))
                                .addGap(45, 45, 45)
                                .addComponent(btnCreateClass))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabelWelcomeAdminStaff)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWelcomeAdminStaff)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGradingSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateClass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccountManage, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountManageActionPerformed
        goToManageAccountDashboard(this);
    }//GEN-LAST:event_btnAccountManageActionPerformed

    private void btnAssignLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignLecturerActionPerformed
        goToAssignLecturerDashboard(this);
    }//GEN-LAST:event_btnAssignLecturerActionPerformed

    private void btnGradingSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradingSystemActionPerformed
        goToAPUGradingSystem(this);
    }//GEN-LAST:event_btnGradingSystemActionPerformed

    private void btnCreateClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateClassActionPerformed
        goToCreateClassDashboard(this);
    }//GEN-LAST:event_btnCreateClassActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        NavigateToLogInPage.goToLogInPage(this);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
            new AdminStaffDashboard("Admin Staff").setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountManage;
    private javax.swing.JButton btnAssignLecturer;
    private javax.swing.JButton btnCreateClass;
    private javax.swing.JButton btnGradingSystem;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelWelcomeAdminStaff;
    // End of variables declaration//GEN-END:variables
}
