package LogIn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */

import java.io.*;
import javax.swing.*;
import AdminStaff.AdminStaffDashboard;
import AcademicLeader.AcademicLeaderDashboard;
import Student.StudentDashboard;
import Lecturer.LecturerDashboard;
import Navigation.NavigateToDashboard;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;


public class LogIn extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogIn.class.getName());

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }
    
    private void navigateToAccordingDashboard(String role, String accID, String name) {
        this.dispose(); // close login window

        switch (role.toLowerCase()) {

            case "admin":
                NavigateToDashboard.goToAdminStaffDashboard(this);
                break;

            case "lecturer":
                NavigateToDashboard.goToLecturerDashboard(this);
                break;

            case "student":
                NavigateToDashboard.goToStudentDashboard(this);
                break;
                
            case "academic leader":
                NavigateToDashboard.goToAcademicLeaderDashboard(this);
                break;            

            default:
                JOptionPane.showMessageDialog(null,
                    "Unknown role: " + role,
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public boolean verifyEmail() {
        String email = tfLogInEmail.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Email cannot be empty!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this, 
                "Invalid email format!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    public boolean verifyPassword() {
        String password = new String(pfLogInPw.getPassword());

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Password cannot be empty!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    
    public void logIntoAccount(){   
        if (!verifyEmail() || !verifyPassword()) {
            return;
        }

        String emailInput = tfLogInEmail.getText().trim();
        String passwordInput = new String(pfLogInPw.getPassword());

        String filePath = "accounts.txt"; // adjust path if needed
        boolean loginSuccess = false;

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {

            String line;
            while ((line = br.readLine()) != null) {

                String[] data = line.split("\\|");

                if (data.length != 9) {
                    continue; // skip corrupted lines
                }

                String accID    = data[0];
                String username = data[1];
                String name     = data[2];
                String email    = data[3];
                String password = data[4];
                String phone    = data[5];
                String gender   = data[6];
                String age      = data[7];
                String role     = data[8];

                if (email.equalsIgnoreCase(emailInput) &&
                    password.equals(passwordInput)) {

                    loginSuccess = true;
                    JOptionPane.showMessageDialog(this,
                            "Login successful! Welcome " + name);

                    navigateToAccordingDashboard(role, accID, name);
                    break;
                }
            }

            if (!loginSuccess) {
                JOptionPane.showMessageDialog(this,
                    "Invalid email or password!",
                    "Login Failed", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                "Error reading account file!",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLbl4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfLogInEmail = new javax.swing.JTextField();
        pfLogInPw = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel3.setText("Log In");

        jLbl4.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLbl4.setText("Email");

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel7.setText("Password");

        jButton1.setText("Log In");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLbl4)
                                .addComponent(tfLogInEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(pfLogInPw)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jLbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLogInEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfLogInPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logIntoAccount();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLbl4;
    private javax.swing.JPasswordField pfLogInPw;
    private javax.swing.JTextField tfLogInEmail;
    // End of variables declaration//GEN-END:variables
}
