/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Lecturer;

import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author justl
 */
public class CreateNewAssignment extends javax.swing.JPanel {

    private LecturerAssignments parentPanel;
    /**
     * Creates new form CreateNewAssignment
     */
    public CreateNewAssignment(LecturerAssignments parent) {
        this.parentPanel = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        AssignmentNamefield = new javax.swing.JTextField();
        jLabelassignmentname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncreateassignment = new javax.swing.JButton();
        jLabelclasscode = new javax.swing.JLabel();
        jLabellecturerclasscode = new javax.swing.JLabel();
        jLabeldurationhours = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        dashboard.setBackground(new java.awt.Color(228, 228, 228));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jLabel5.setText("January 20, 2025");
        dashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 23, -1, -1));

        jLabel17.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jLabel17.setText("04:00 AM");
        dashboard.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 45, 80, -1));

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        AssignmentNamefield.setText("assignmentname");
        AssignmentNamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentNamefieldActionPerformed(evt);
            }
        });

        jLabelassignmentname.setText("Assignment Name :");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel6.setText("CreateNewAssignment");

        btncreateassignment.setText("create assignment");
        btncreateassignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateassignmentActionPerformed(evt);
            }
        });

        jLabelclasscode.setText("Class Code :");

        jLabellecturerclasscode.setText("base on which lecturer");

        jLabeldurationhours.setText("Duration Hours :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "45 min", "1 hrs", "1.5 hrs", "2 hrs" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnback))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabeldurationhours)
                            .addComponent(jLabelassignmentname)
                            .addComponent(jLabelclasscode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabellecturerclasscode)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AssignmentNamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btncreateassignment))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelassignmentname)
                    .addComponent(AssignmentNamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeldurationhours)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelclasscode)
                    .addComponent(jLabellecturerclasscode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btncreateassignment)
                .addGap(32, 32, 32)
                .addComponent(btnback)
                .addGap(68, 68, 68))
        );

        dashboard.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 730, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        if (parentPanel != null) {
            parentPanel.showDashboard();
        }

    }//GEN-LAST:event_btnbackActionPerformed

    private void AssignmentNamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignmentNamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignmentNamefieldActionPerformed

    private void btncreateassignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateassignmentActionPerformed
        // TODO add your handling code here:
        String assignmentname = AssignmentNamefield.getText();
        String durationhours = (String) jComboBox1.getSelectedItem();
        String classcode = jLabellecturerclasscode.getText();

        if (assignmentname.isEmpty() || classcode.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
            return;
        }
        try
        {
            String filePath = "TextFiles/assignment.txt";
            FileWriter writer = new FileWriter(filePath, true);

            String line = assignmentname + ";" + durationhours + ";" + classcode;
            writer.write(line);
            writer.write(System.getProperty("line.separator"));
            writer.close();

            JOptionPane.showMessageDialog(null,"Success");
            setVisible(false);
            parentPanel.showViewAssignment();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_btncreateassignmentActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssignmentNamefield;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncreateassignment;
    private javax.swing.JPanel dashboard;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelassignmentname;
    private javax.swing.JLabel jLabelclasscode;
    private javax.swing.JLabel jLabeldurationhours;
    private javax.swing.JLabel jLabellecturerclasscode;
    private javax.swing.JPanel jPanel15;
    // End of variables declaration//GEN-END:variables
}
