/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Lecturer;

import javax.swing.JPanel;
import java.awt.CardLayout;
/**
 *
 * @author justl
 */
//COMPOSITION
public class FeedbackandGPA2 extends javax.swing.JPanel {
    //ENCAPSULATION = protected
    protected String lecturerName;
    protected String lecturerCourseId;
    
    
    protected StudentGPA studentGPA;
    protected ViewFeedbacks viewFeedbacks;
    
    protected CardLayout cardLayout;
    protected JPanel cardPanel;
    /**
     * Creates new form FeedbackandGPA2
     */
    public FeedbackandGPA2(String lecturerName, String courseId) {
        this.lecturerName = lecturerName;
        this.lecturerCourseId = courseId;
        initComponents();
    }

    protected void initSharedComponents(){
        if (studentGPA == null){
            studentGPA = new StudentGPA(this); // Create StudentGPA
        }
        if (viewFeedbacks == null){
            viewFeedbacks = new ViewFeedbacks(this);//Create ViewFeedbacks
        }
    }
    
    //but expose through public getters
    public StudentGPA getStudentGPA(){
        return studentGPA;
    }
    
    public ViewFeedbacks getViewFeedbacks(){
        return viewFeedbacks;
    }
    
    public String getLecturerCourseId() {
        return this.lecturerCourseId;
    }
    
    public String getLecturerName(){
        return this.lecturerName;
    }
    
    public void showDashboard(){
        if (cardLayout != null && cardPanel != null){
            cardLayout.show(cardPanel, "DASHBOARD");
        }
    }
    
    public void showStudentGPA(){
        if (cardLayout != null && cardPanel != null){
            cardLayout.show(cardPanel, "GPA");
        }
    }
    
    public void showFeedbacks(){
        if (cardLayout != null && cardPanel != null){
            cardLayout.show(cardPanel, "Feedbacks");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
