/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Lecturer;

import java.io.File;
import java.io.IOException;
import javax.swing.table.DefaultTableModel; 
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author justl
 */
public class GradeClassessAssignment extends javax.swing.JPanel {

    private LecturerAssignments parentPanel;
    /**
     * Creates new form GradeClassessAssignment
     */
    public GradeClassessAssignment(LecturerAssignments parent) {
        initComponents();
        this.parentPanel = parent;
        loadTableData();
    }
    
    private void loadTableData(){
        String filePath = "src/TextFiles/AssignmentSubmission.txt";
        File file = new File(filePath);
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            //get the first line
            //get the columns name from the first line
            //set columns name to the jtable model
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(";");
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            
            // Find the index of the ClassID column
            int classIdColumnIndex = -1;
            for(int i = 0; i < columnsName.length; i++){
                if(columnsName[i].equalsIgnoreCase("ClassID") || 
                   columnsName[i].equalsIgnoreCase("Class ID")){
                    classIdColumnIndex = i;
                    break;
                }
            }
            
            //get line from txt file
            Object[] tableLines = br.lines().toArray();
            
            //extract data from lines
            //set data to jtable model
            // Extract and filter data based on classId
            for(int i = 0; i < tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
                
                // Only add row if course ID matches lecturer's course
                if(classIdColumnIndex != -1 && dataRow[classIdColumnIndex].equals(parentPanel.getClassId())){
                    model.addRow(dataRow);
                }
            }
            br.close();
            
        } catch (IOException ex){
            System.getLogger(ViewClassessTest.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dashboard1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonrefresh = new javax.swing.JButton();
        jLabelgradetest = new javax.swing.JLabel();
        jLabelstudentsubmissionlist = new javax.swing.JLabel();
        jLabelstudentid = new javax.swing.JLabel();
        jLabelstudent1field = new javax.swing.JLabel();
        jLabelstatus = new javax.swing.JLabel();
        jLabelstatusfield = new javax.swing.JLabel();
        jLabelcourseid = new javax.swing.JLabel();
        jLabelcoursefield = new javax.swing.JLabel();
        jLabeltestname = new javax.swing.JLabel();
        jLabelassignmentnamefield = new javax.swing.JLabel();
        jLabeltestmarks = new javax.swing.JLabel();
        jButtongrade = new javax.swing.JButton();
        jTextFieldassignmentmarks = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        dashboard.setBackground(new java.awt.Color(228, 228, 228));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel6.setText("GradeClassessAssignment ");
        dashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 23, 600, -1));

        jLabel17.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jLabel17.setText("04:00 AM");
        dashboard.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 45, 80, -1));

        dashboard1.setBackground(new java.awt.Color(228, 228, 228));
        dashboard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jLabel7.setText("January 20, 2025");
        dashboard1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 23, -1, -1));

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonrefresh.setText("Refresh");
        jButtonrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrefreshActionPerformed(evt);
            }
        });

        jLabelgradetest.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        jLabelgradetest.setText("Grade Assignment");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelgradetest)
                    .addComponent(jButtonrefresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonrefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelgradetest)
                .addContainerGap())
        );

        jLabelstudentsubmissionlist.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        jLabelstudentsubmissionlist.setText("Student Submission List");

        jLabelstudentid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelstudentid.setText("Student ID:");

        jLabelstudent1field.setText("student1");

        jLabelstatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelstatus.setText("Status:");

        jLabelstatusfield.setText("submitted");

        jLabelcourseid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelcourseid.setText("Class ID:");

        jLabelcoursefield.setText("C001");

        jLabeltestname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeltestname.setText("Assignment Name:");

        jLabelassignmentnamefield.setText("mathpupu");

        jLabeltestmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeltestmarks.setText("Assignment Marks:");

        jButtongrade.setText("Grade");
        jButtongrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongradeActionPerformed(evt);
            }
        });

        jTextFieldassignmentmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldassignmentmarksActionPerformed(evt);
            }
        });

        jLabel1.setText("Feedbacks:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel16Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelcourseid)
                                        .addComponent(jLabelstudentid)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabelstatus)))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnback)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelstatusfield, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabelstudent1field, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabeltestname))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabelcoursefield, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtongrade)
                                    .addComponent(jLabeltestmarks))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelassignmentnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldassignmentmarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelstudentsubmissionlist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelstudentsubmissionlist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelstudentid)
                    .addComponent(jLabelstudent1field)
                    .addComponent(jLabeltestname)
                    .addComponent(jLabelassignmentnamefield)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelcourseid)
                            .addComponent(jLabelcoursefield)
                            .addComponent(jLabeltestmarks)
                            .addComponent(jTextFieldassignmentmarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelstatus)
                            .addComponent(jLabelstatusfield))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnback)
                            .addComponent(jButtongrade))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        dashboard1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 750, 380));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dashboard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtongradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongradeActionPerformed
        // TODO add your handling code here:
        String studentname = jLabelstudent1field.getText();
        String classid = jLabelcoursefield.getText();
        String status = jLabelstatusfield.getText();
        String assignmentname = jLabelassignmentnamefield.getText();
        String assignmentmarks = (String) jTextFieldassignmentmarks.getText();
        String feedback = jTextArea1.getText();
        
        if (studentname.isEmpty() || classid.isEmpty() || assignmentname.isEmpty() || feedback.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a row to grade and give feedback!");
            return;
        }else if(status.equals("Graded")){
            JOptionPane.showMessageDialog(null, "Have been Graded!");
            return;
        }
        try
        {
            String filePath = "src/TextFiles/gradeassignment.txt";
            FileWriter writer = new FileWriter(filePath, true);
            LocalDateTime now = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String timestamp = now.format(formatter);

            String line = studentname + ";" + classid + ";" + assignmentname + ";" + assignmentmarks + ";" + feedback + ";" + timestamp;
            writer.write(line);
            writer.write(System.getProperty("line.separator"));
            writer.close();

            //Updata AssgnmentSubmission.txt status to "Graded"
            updateAssignmentSubmissionStatus(studentname, classid, assignmentname);
            
            JOptionPane.showMessageDialog(null,"Success");
            
            // Clear the form after successful grading
            jTextArea1.setText("");
            jLabelstatusfield.setText("Graded");
            loadTableData();
            
            setVisible(false);
            parentPanel.showGradeAssignment();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_jButtongradeActionPerformed

    private void updateAssignmentSubmissionStatus(String studentId, String classId, String assignmentName) {
    String filePath = "src/TextFiles/AssignmentSubmission.txt";
    File file = new File(filePath);
    
    try {
        BufferedReader br = new BufferedReader(new FileReader(file));
        StringBuilder content = new StringBuilder();
        String line;
        
        // Read header
        String header = br.readLine();
        content.append(header).append(System.getProperty("line.separator"));
        
        while((line = br.readLine()) != null) {
            String[] data = line.split(";");
            
            // Check if this is the row we want to update
            // Format: Student Id;Class Id;Assignment Name;Date Time;Status
            if(data.length >= 6 && 
               data[0].trim().equals(studentId.trim()) && 
               data[1].trim().equals(classId.trim()) && 
               data[2].trim().equals(assignmentName.trim())) {
                
                // Update the status (column index 4) from "Submitted" to "Graded"
                data[4] = "Graded";
                line = String.join(";", data);
            }
            
            content.append(line).append(System.getProperty("line.separator"));
        }
        br.close();
        
        // Write back to file
        FileWriter writer = new FileWriter(filePath, false);
        writer.write(content.toString());
        writer.close();
        
    } catch (IOException ex) {
        System.getLogger(GradeClassessTest.class.getName()).log(System.Logger.Level.ERROR, "Error updating status", ex);
    }
}

    
    private void jButtonrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrefreshActionPerformed
        // TODO add your handling code here:
        loadTableData();
    }//GEN-LAST:event_jButtonrefreshActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        jLabelstudent1field.setText(model.getValueAt(selectedRow, 0).toString());
        jLabelcoursefield.setText(model.getValueAt(selectedRow, 1).toString());
        jLabelassignmentnamefield.setText(model.getValueAt(selectedRow, 2).toString());
        jLabelstatusfield.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        if (parentPanel != null) {
            parentPanel.showDashboard();
        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void jTextFieldassignmentmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldassignmentmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldassignmentmarksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dashboard1;
    private javax.swing.JButton jButtongrade;
    private javax.swing.JButton jButtonrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelassignmentnamefield;
    private javax.swing.JLabel jLabelcoursefield;
    private javax.swing.JLabel jLabelcourseid;
    private javax.swing.JLabel jLabelgradetest;
    private javax.swing.JLabel jLabelstatus;
    private javax.swing.JLabel jLabelstatusfield;
    private javax.swing.JLabel jLabelstudent1field;
    private javax.swing.JLabel jLabelstudentid;
    private javax.swing.JLabel jLabelstudentsubmissionlist;
    private javax.swing.JLabel jLabeltestmarks;
    private javax.swing.JLabel jLabeltestname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldassignmentmarks;
    // End of variables declaration//GEN-END:variables
}
